// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/container.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_proto_rawDescGZIP(), []int{0}
}

type ContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerName       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerResponse) Reset() {
	*x = ContainerResponse{}
	mi := &file_proto_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerResponse) ProtoMessage() {}

func (x *ContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerResponse.ProtoReflect.Descriptor instead.
func (*ContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerResponse) GetContainers() []*ContainerName {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerName) Reset() {
	*x = ContainerName{}
	mi := &file_proto_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerName) ProtoMessage() {}

func (x *ContainerName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerName.ProtoReflect.Descriptor instead.
func (*ContainerName) Descriptor() ([]byte, []int) {
	return file_proto_container_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerName) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContainerName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_container_proto protoreflect.FileDescriptor

const file_proto_container_proto_rawDesc = "" +
	"\n" +
	"\x15proto/container.proto\x12\x15container_adm_service\"\x0e\n" +
	"\fEmptyRequest\"Y\n" +
	"\x11ContainerResponse\x12D\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2$.container_adm_service.ContainerNameR\n" +
	"containers\"3\n" +
	"\rContainerName\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2x\n" +
	"\x13ContainerAdmService\x12a\n" +
	"\x10GetAllContainers\x12#.container_adm_service.EmptyRequest\x1a(.container_adm_service.ContainerResponseB\fZ\n" +
	"./proto/pbb\x06proto3"

var (
	file_proto_container_proto_rawDescOnce sync.Once
	file_proto_container_proto_rawDescData []byte
)

func file_proto_container_proto_rawDescGZIP() []byte {
	file_proto_container_proto_rawDescOnce.Do(func() {
		file_proto_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_container_proto_rawDesc), len(file_proto_container_proto_rawDesc)))
	})
	return file_proto_container_proto_rawDescData
}

var file_proto_container_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_container_proto_goTypes = []any{
	(*EmptyRequest)(nil),      // 0: container_adm_service.EmptyRequest
	(*ContainerResponse)(nil), // 1: container_adm_service.ContainerResponse
	(*ContainerName)(nil),     // 2: container_adm_service.ContainerName
}
var file_proto_container_proto_depIdxs = []int32{
	2, // 0: container_adm_service.ContainerResponse.containers:type_name -> container_adm_service.ContainerName
	0, // 1: container_adm_service.ContainerAdmService.GetAllContainers:input_type -> container_adm_service.EmptyRequest
	1, // 2: container_adm_service.ContainerAdmService.GetAllContainers:output_type -> container_adm_service.ContainerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_container_proto_init() }
func file_proto_container_proto_init() {
	if File_proto_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_container_proto_rawDesc), len(file_proto_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_container_proto_goTypes,
		DependencyIndexes: file_proto_container_proto_depIdxs,
		MessageInfos:      file_proto_container_proto_msgTypes,
	}.Build()
	File_proto_container_proto = out.File
	file_proto_container_proto_goTypes = nil
	file_proto_container_proto_depIdxs = nil
}
